polls/urls.py
from django.conf.urls.defaults import *


urlpatterns = patterns('polls.views',
    url(r'^$', 'index', name='polls_index'),
    url(r'^(?P<poll_id>\d+)/$', 'detail', name='polls_detail'),
    url(r'^(?P<poll_id>\d+)/results/$', 'results', name='polls_results'),
)

polls_api/urls.py
from django.conf.urls.defaults import *


urlpatterns = patterns('polls_api.views',
    url(r'^restframework', include('djangorestframework.urls', namespace='djangorestframework')),
    url(r'^(?P<poll_id>\d+)/$', 'poll_results_view', name='polls_api_results'),
    url(r'^(?P<poll_id>\d+)/votes/$', 'poll_votes_view', name='polls_api_votes'),
)

urls.py
from django.conf.urls.defaults import *


from django.contrib import admin
admin.autodiscover()


urlpatterns = patterns('',
    # Example:
    # (r'^guide_to_testing/', include('guide_to_testing.foo.urls')),

    (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    (r'^admin/', include(admin.site.urls)),
    (r'^polls/', include('polls.urls')),
    (r'^api/', include('polls_api.urls')),
)

polls/models.py
import datetime
from django.db import models


class PollManager(models.Manager):
    def get_query_set(self):
        now = datetime.datetime.now()
        return super(PollManager, self).get_query_set().filter(pub_date__lte=now)


class Poll(models.Model):
    question = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published', default=datetime.datetime.now)
    
    objects = models.Manager()
    published = PollManager()
    
    def __unicode__(self):
        return self.question
    
    def was_published_today(self):
        return self.pub_date.date() == datetime.date.today()
    was_published_today.short_description = 'Published today?'


class Choice(models.Model):
    poll = models.ForeignKey(Poll)
    choice = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    
    def __unicode__(self):
        return self.choice
    
    def record_vote(self):
        self.votes += 1
        self.save()

polls/forms.py
from django import forms
from polls.models import Choice


class PollForm(forms.Form):
    def __init__(self, *args, **kwargs):
        # We require an ``instance`` parameter.
        self.instance = kwargs.pop('instance')
        
        # We call ``super`` (without the ``instance`` param) to finish
        # off the setup.
        super(PollForm, self).__init__(*args, **kwargs)
        
        # We add on a ``choice`` field based on the instance we've got.
        # This has to be done here (instead of declaratively) because the
        # ``Poll`` instance will change from request to request.
        self.fields['choice'] = forms.ModelChoiceField(queryset=Choice.objects.filter(poll=self.instance.pk), empty_label=None, widget=forms.RadioSelect)
    
    def save(self):
        if not self.is_valid():
            raise forms.ValidationError("PollForm was not validated first before trying to call 'save'.")
        
        choice = self.cleaned_data['choice']
        choice.record_vote()
        return choice

polls/views.py
import json
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render_to_response, get_object_or_404
from django.template import RequestContext
from polls.forms import PollForm
from polls.models import Poll, Choice
from polls_api.resources import PollResource


def index(request):
    latest_poll_list = Poll.published.all().order_by('-pub_date')[:5]
    return render_to_response('polls/index.html', {'latest_poll_list': latest_poll_list})


def detail(request, poll_id):
    p = get_object_or_404(Poll.published.all(), pk=poll_id)

    if request.method == 'POST':
        form = PollForm(request.POST, instance=p)

        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('polls_results', kwargs={'poll_id': p.id}))
    else:
        form = PollForm(instance=p)

    initial_results_data = PollResource().serialize(p)

    return render_to_response('polls/detail.html', {
        'poll': p,
        'form': form,
        'initial_results_data': json.dumps(initial_results_data)
    }, context_instance=RequestContext(request))


def results(request, poll_id):
    p = get_object_or_404(Poll.published.all(), pk=poll_id)
    return render_to_response('polls/results.html', {'poll': p},
                              context_instance=RequestContext(request))

polls_api/views.py
from django.shortcuts import get_object_or_404
from django.core.urlresolvers import reverse
from djangorestframework import views
from djangorestframework.response import Response
from polls.forms import PollForm
from polls.models import Poll
from .resources import PollResource

class PollResults (views.View):

    def get(self, request, poll_id):
        poll = get_object_or_404(Poll.objects.all(), pk=poll_id)
        results = PollResource().serialize(poll)
        return results


class PollVotes (views.View):

    def post(self, request, poll_id):
        poll = get_object_or_404(Poll.objects.all(), pk=poll_id)
        form = PollForm(request.POST, instance=poll)

        if form.is_valid():
            form.save()
        else:
            return Response(content=form.errors, status=400)

        return Response(status=303, headers={'Location': reverse('polls_api_results', args=[poll_id])})

poll_results_view = PollResults.as_view()
poll_votes_view = PollVotes.as_view()

templates/polls/base.html
<html>
    <head>
        <title>Polls App</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <script src="{{ STATIC_URL }}libs/jquery.js"></script>
        <script src="{{ STATIC_URL }}libs/underscore.js"></script>
        <script src="{{ STATIC_URL }}libs/backbone.js"></script>

        <script src="{{ STATIC_URL }}polls/utils.js"></script>
        <script src="{{ STATIC_URL }}polls/models.js"></script>
        <script src="{{ STATIC_URL }}polls/views.js"></script>
        <script src="{{ STATIC_URL }}polls/routes.js"></script>
        <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}polls/styles.css">
    </head>

    <body>
    {% block content %}
    {% endblock %}
    </body>
</html>

templates/polls/detail.html
{% extends "polls/base.html" %}

{% block content %}
<h1>{{ poll.question }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="." method="post" id="id_vote_form">
{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Vote" />
</form>

<div id="id_results_box">
  <ul>
    {% for choice in poll.choice_set.all %}
    <li class="choice_bar" id="id_choice_{{ choice.id }}_bar">
      <div class="off">{{ choice.choice }} -- <span class="count">{{ choice.votes }}</span> vote{{ choice.votes|pluralize }}</div>
      <div class="on">{{ choice.choice }} -- <span class="count">{{ choice.votes }}</span> vote{{ choice.votes|pluralize }}</div>
    </li>
    {% endfor %}
  </ul>

  <a href="{% url polls_detail poll_id=poll.id %}">Vote again?</a>
</div>

<script>
  workflow = new Polls.Workflow({
    resultsUrl: '{% url polls_api_results poll.id %}',
    initialResults: {{ initial_results_data|default:'{}'|safe }}
  });

  Backbone.history.start({pushState: true});
</script>

{% endblock %}

templates/polls/index.html
{% if latest_poll_list %}
    <ul>
    {% for poll in latest_poll_list %}
        <li><a href="{% url polls_detail poll_id=poll.id %}">{{ poll.question }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

templates/polls/results.html
{% extends "polls/base.html" %}

{% block content %}
<h1>{{ poll.question }}</h1>

<ul>
{% for choice in poll.choice_set.all %}
    <li>{{ choice.choice }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url polls_detail poll_id=poll.id %}">Vote again?</a>
{% endblock %}